### ISSUE TITLE
postfix-logparser.py - Only shows last email address when there are multiple To's in a message

### ISSUE THREAD

**Issue by achollister** [strycore/scripts#4]
If you send an email with multiple email addresses in the TO field only the last one shows up in the database. All the others seem to be ignored.

**Comment by strycore** [comment]
HI @stiadmin 
I haven't used this script since 2010, could you possibly submit a pull request to fix this issue? I'll look into it.

**Comment by vivek779** [comment]
I also use this script bt it is showing errors i have edited path in script like
postfix_log = os.path.join(log_prefix, 'mail.info.0'
to
postfix_log = os.path.join(log_prefix, 'maillog'
My postfix logs  which are at /var/log/mailog
and 
MYSQL_USER = 'mailing'
MYSQL_PASSWORD = 'mailinga2v'
MYSQL_DATABASE = MYSQL_USER
MYSQL_HOST = 'localhost'
MYSQL_TABLE = 'mail_tracking'
to
MYSQL_USER = 'root'
MYSQL_PASSWORD = 'vivek'
MYSQL_DATABASE = logs
MYSQL_HOST = 'localhost'
MYSQL_TABLE = 'mail_tracking'
these are mysql credentials 
please guide me to run this scripts

**Comment by strycore** [comment]
Like I said before, I haven't used this script in 5 years. What errors are you getting?

**Comment by vivek779** [comment]
File "./postfix-log.py", line 177, in <module>
    mailinfo[queue_id]['message_id'])
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1146, "Table 'logs.mail_tracking' doesn't exist")

**Comment by strycore** [comment]
Well the error message is pretty explicit. You have to create the mail_tracking table. There's a mysql command in the command at the beginning of the script that does that, just make sure to change the table name

**Comment by vivek779** [comment]
Thanks for revert 
 I followed your steps and created a different database name postfix and created a table like this mail_tracking  and changed log prefix like this
postfix_log = os.path.join(log_prefix, 'maillog')
 It is  showing error as follows 
File "postfix-logparser.py", line 191, in <module>
    cursor.execute(q, tuple(values))
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'created_at' in 'field list'")

please help me in this also how to solve  this and run the  script

**Comment by farfar56** [comment]
Dear strycore
when running, i get the following error 

Traceback (most recent call last):
  File "postfix-logparser.py", line 118, in <module>
    (email_from, size, nrcpt) = details.split(',',3)
ValueError: too many values to unpack

In addition, my **postfix version is 2.11** 
Please help me to solve this problem .

**Comment by strycore** [comment]
Hi farfar56

I wrote this script for a one time use only for a job I had 6 years ago. I do not plan to use it anymore or to spend more time on it. I left it here in case people who are able to maintain it themselves would want to use it but the script itself is very poorly written (I had 1 year of experience with Python at the time).

I'm sure there are tools better written and currently maintained that to do the same thing (or, at least, I hope there are, this wasn't the case 6 years ago). I'll now be retiring this script and remove it from the repo. Anyone who wishes to take maintainership can do so by forking the project.
